### ISSUE TITLE
reset password not working

### ISSUE THREAD

**Issue by pasha009** [muicss/flaskapp#6]
Hi, thanks for this amazing template.

On testing the forgot password functionality, I was getting expired link error even with newly created reset links.
It traced back to empty `request.args` in `reset_password` route. Looking at the template `reset-password.html` i found that
the form action specified didn't maintained the url parameters of key and email. 

So removing the action specification in the form by default posts to the same url it was viewed on, which solved the problem.

I thought it would be better to tell/discuss this with you, rather than making a PR of 1 line deletion.

**Comment by amorey** [comment]
Nice catch and thanks for the fix! I fixed the bug and pushed to master.
